# This notebook will be comprised of 3 parts
- Part 1 - Import all pershing square finalist predictions from past 5 years as well as their current stock trends
- Part 2 - Compare the performance of this winners against major indexes and see if we'd be better off listening to winners
- Part 3 - Look at some reasons why winners may not have performed against expectations

In [1]:
### Part 1 -- Importing prediction from google docs

In [3]:
import numpy as np
import pandas as pd
import os
from datetime import datetime, timedelta
import yfinance as yf
import matplotlib.pyplot as plt
import chart_studio.plotly as py
import plotly.express as px
import plotly.graph_objects as go
current_directory = os.getcwd()
print(current_directory) 
pd.set_option('display.max_rows', 500)

/Users/srite/repos/sri_avi_blog_posts/pershing_square_challenge

In [7]:
predictions = pd.read_csv('pershing_square_predictions.csv')
predictions['presentation_date'] = pd.to_datetime(predictions['presentation_date'])
predictions.head(20)

,competition_year,ticker,stock_name,base_3,bull_3,base_4,bull_4,base_5,bull_5,base_10,bull_10,short_base_9,short_bull_9,presentation_price,team_rank,presentation_date
0,2019,ARMK,Aramark,57.70,81.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.00,2.0,2019-04-30
1,2019,KMX,Carmax,149.00,234.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.94,NaN,2019-04-30
2,2019,DOL,Dollarama,57.00,75.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.26,1.0,2019-04-30
3,2019,SERV,Servicemaster Global,78.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.05,NaN,2019-04-30
4,2019,USFD,US Foods,68.85,87.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.00,NaN,2019-04-30
5,2020,BLL,Ball Corporation,NaN,NaN,115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.00,NaN,2020-04-30
6,2020,BR,Broadridge Financial Solutions,174.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.54,NaN,2020-04-30
7,2020,EPAM,EPAM Systems,NaN,NaN,415.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196.18,1.0,2020-04-30
8,2020,SYY,Sysco,103.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.84,2.0,2020-04-30
9,2020,VRSK,Verisk Analytics,222.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.00,NaN,2020-04-30
10,2021,ANGI,Angi,NaN,NaN,NaN,NaN,45.26,NaN,NaN,NaN,NaN,NaN,17.03,NaN,2021-04-14
11,2021,AVLR,Avalara,NaN,NaN,NaN,NaN,NaN,NaN,850.0,NaN,NaN,NaN,142.56,NaN,2021-04-14
12,2021,BL,Blackline,NaN,NaN,NaN,NaN,322.00,NaN,NaN,NaN,NaN,NaN,111.00,NaN,2021-04-14
13,2021,DLB,Dolby,NaN,NaN,NaN,NaN,205.00,NaN,NaN,NaN,NaN,NaN,102.14,NaN,2021-04-14
14,2021,PEGA,Pegasystems,NaN,NaN,NaN,NaN,310.00,NaN,NaN,NaN,NaN,NaN,129.00,NaN,2021-04-14
15,2022,CARG,Cargurus,NaN,NaN,NaN,NaN,107.84,NaN,NaN,NaN,NaN,NaN,35.34,2.0,2022-04-26
16,2022,GAW,Games Workshop,NaN,NaN,NaN,NaN,182.51,NaN,NaN,NaN,NaN,NaN,73.35,NaN,2022-04-26
17,2022,PGNY,Progyny,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,NaN,40.38,1.0,2022-04-26
18,2022,PYPL,Paypal,232.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.70,NaN,2022-04-26
19,2022,TNDM,Tandem,NaN,NaN,NaN,NaN,285.00,NaN,NaN,NaN,NaN,NaN,100.61,NaN,2022-04-26

In [15]:
predictions['projection_date'] = '';

predictions.loc[predictions['base_3'].notnull(),'projection_date'] = predictions['presentation_date']  + pd.offsets.DateOffset(years=3)
predictions.loc[predictions['base_4'].notnull(),'projection_date'] = predictions['presentation_date']  + pd.offsets.DateOffset(years=4)
predictions.loc[predictions['base_5'].notnull(),'projection_date'] = predictions['presentation_date']  + pd.offsets.DateOffset(years=5)
#predictions.loc[predictions['base_10'].notnull(),'projection_date'] = predictions['presentation_date']  + timedelta(years=10)
predictions['projection_date'] = pd.to_datetime(predictions['projection_date'])

predictions.head(10)

,competition_year,ticker,stock_name,base_3,bull_3,base_4,bull_4,base_5,bull_5,base_10,bull_10,short_base_9,short_bull_9,presentation_price,team_rank,presentation_date,projection_date
0,2019,ARMK,Aramark,57.70,81.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.00,2.0,2019-04-30,2022-04-30
1,2019,KMX,Carmax,149.00,234.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.94,NaN,2019-04-30,2022-04-30
2,2019,DOL,Dollarama,57.00,75.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.26,1.0,2019-04-30,2022-04-30
3,2019,SERV,Servicemaster Global,78.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.05,NaN,2019-04-30,2022-04-30
4,2019,USFD,US Foods,68.85,87.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.00,NaN,2019-04-30,2022-04-30
5,2020,BLL,Ball Corporation,NaN,NaN,115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.00,NaN,2020-04-30,2024-04-30
6,2020,BR,Broadridge Financial Solutions,174.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.54,NaN,2020-04-30,2023-04-30
7,2020,EPAM,EPAM Systems,NaN,NaN,415.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196.18,1.0,2020-04-30,2024-04-30
8,2020,SYY,Sysco,103.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.84,2.0,2020-04-30,2023-04-30
9,2020,VRSK,Verisk Analytics,222.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.00,NaN,2020-04-30,2023-04-30

In [18]:
### create actuals dataframe

def fetch_stock_data(ticker, start_date, end_date):
    data = yf.download(ticker, start=start_date, end=end_date)
    return data
stock_data = [];

for index, row in predictions.iterrows():
    ticker = row['ticker']
    stock_name = row['stock_name']
    team_rank = row['team_rank']
    start_date = row['presentation_date']
    end_date = row['projection_date']
    reported_presentation_day_price = row['presentation_price']
    presentation_year = row['competition_year']


    data_temp = fetch_stock_data(ticker, start_date, end_date)
    data_temp['ticker'] = ticker
    data_temp['stock_name'] = stock_name
    data_temp['team_rank'] = team_rank;
    data_temp['presentation_year'] = presentation_year
    data_temp['reported_presentation_day_price'] = reported_presentation_day_price

    
    
    stock_data.append(data_temp)

    
stock_data = pd.concat(stock_data)
stock_data = stock_data.reset_index()
predictions.dtypes
#for stock in predictions['ticker']:
#    print(stock)

[*********************100%%**********************]  1 of 1 completed

NameError: name 'stock_data' is not defined